sudo: required
language: node_js
env:
  global:
    - RELEASE_NAME=build
node_js:
  - "stable"
cache:
directories:
  - node_modules
before_install:
  - npm ci
script:
  - npm run build
before_deploy:
  - tar -czf $RELEASE_NAME-$TRAVIS_TAG.tar.gz $RELEASE_NAME
  - zip -r $RELEASE_NAME-$TRAVIS_TAG.zip $RELEASE_NAME
  - ls -al
deploy:
  provider: releases
  api_key: $GITHUB_TOKEN
  file: 
    - $RELEASE_NAME-$TRAVIS_TAG.tar.gz
    - $RELEASE_NAME-$TRAVIS_TAG.zip
  skip_cleanup: true
  on:
    tags: true
    repo: Boogst/quick-start-react
